### ISSUE TITLE
.DS_Store files

### ISSUE THREAD

**Issue by MatijaMedven** [dstrekelj/algebra-front-end-developer-2019#73]
Za nas koji radimo na Mac-u, često se zna desiti da preko GitHub Desktopa slučajno commitamo i -DS_Store fileove. Da ne bi svaki put morali paziti i ručno brisati te fileove po repozitoriju, možemo dodati u gitignore file .DS_Store. Kako i ime kaže, gitignore će ignorirati takve fileove.

**Comment by dstrekelj** [comment]
Odlično! 👍
